# Generated by Django 3.1.4 on 2020-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_rental_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_history',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='rental_history',
            name='vin',
        ),
        migrations.AddField(
            model_name='rental_history',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental_history',
            name='payment_method',
            field=models.CharField(default='credit card', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental_history',
            name='vehicle_type',
            field=models.CharField(default='small car', max_length=30),
            preserve_default=False,
        ),
    ]
